### ISSUE TITLE
The configuration of the architecture variants is inconsistent with the papers and weights files.

### ISSUE THREAD

**Issue by lartpang** [microsoft/SPACH#2]
@tangchuanxin

https://github.com/microsoft/SPACH/blob/497c1d86fffd9d48e26c0484fb845ff04c328cca/models/registry.py#L224

The code is inconsistent with the content of the paper:

![image](https://user-images.githubusercontent.com/26847524/154786930-28b915b4-f9f6-4baf-bd5b-1c00c252652f.png)

and the weight file. The content of this `pth` file is the same as the architecture variant `-S` in the figure above, ie, `depths=(6, 8, 18, 6)`.

https://github.com/microsoft/SPACH/releases/download/v1.0/shiftvit_tiny_r2.pth

**Comment by wgting96** [comment]
Thank you for pointing this error out. The configuration `[depths=(6, 8, 18, 6)]` is correct. I will fix this bug soon.

The configuration of `(3, 3, 24, 4)` is another version of ShiftViT-T we have tried. It has the similar number of parameters and FLOPs. 

| Config        | MLP ratio | Num of params. (M) | FLOPs (G) |
| ------------- | --------- | ------------------ | --------- |
| [6, 8, 18, 6] | 2.0       | 29                 | 4.6       |
| [3, 3, 24, 4] | 2.0       | 27                 | 4.1       |
